services:
  bd_mysql:
    container_name: bd_mysql
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bd_base
      MYSQL_PASSWORD: userpassword
    ports:
      - "3308:3306"
    volumes:
      - ./mysql:/var/lib/mysql
  
  bd_phpmyadmin:
    container_name: bd_phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - bd_mysql
    ports:
      - 8888:80
    environment:
      PMA_HOST: bd_mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
