services:
  bd_postgres:
    container_name: bd_postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mi_base_de_datos
    ports:
      - "5401:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  bd_pgadmin:
    container_name: bd_pgadmin
    image: dpage/pgadmin4
    depends_on:
      - bd_postgres
    ports:
      - "9999:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: admin

volumes:
  postgres_data:
